{{- if and (eq .Values.route true) (ne .Values.istio.enabled true) }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "pet-battle-api.fullname" . }}
  labels:
    {{- include "pet-battle-api.labels" . | nindent 4 }}
spec:
  port:
    targetPort: tcp-8080
  to:
    kind: Service
    name: {{ include "pet-battle-api.fullname" . }}
  {{- if .Values.a_b_deploy }}
    weight: {{ .Values.a_b_deploy.a_weight }}
  alternateBackends:
    - kind: Service
      name: {{ .Values.a_b_deploy.svc_name }}
      weight: {{ .Values.a_b_deploy.b_weight }}
  {{- else }}
    weight: 100
  {{- end }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
{{ end }}
